import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from '@/components/HomePageComponents/Navbar'
import { ROUTES } from '@/libs/routes'
import './globals.css';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  //   const allTabs = [
  //   { tab: 'Features', path: ROUTES.ALWG },
  //   { tab: 'Compare', path: ROUTES.ALWG_COMPARE },
  //   { tab: 'Tech Specs', path: ROUTES.ALWG_TECH_SPECS },
  //   { tab: 'Documentation', path: ROUTES.ALWG_DOCUMENTATION }
  // ]

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Navbar allTabs={allTabs} theme='light' /> */}
        {children}
      </body>
    </html>
  );
}
