// import type { Metadata } from "next";
// import { Roboto } from '@/styles/fonts';
// // import { Geist, Geist_Mono, Roboto } from "next/font/google";
// // import Navbar from '@/components/HomePageComponents/Navbar'
// // import { ROUTES } from '@/libs/routes'
// import './globals.css';

// const roboto = Roboto({
//   subsets: ["latin"],

//   variable: "--font-roboto",
//   display: "swap",
// });

// // export const roboto = Roboto({
// //   subsets: ['latin'],
// //   variable: '--font-roboto',
// //   weight: ['400', '500', '700'], // Include the weights you need
// // });

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// export const metadata: Metadata = {
//   title: "Macnman",
//   description: "Generated by create next app",
//   icons: "/success-stories/favicon.ico",
// };


// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {

//   //   const allTabs = [
//   //   { tab: 'Features', path: ROUTES.ALWG },
//   //   { tab: 'Compare', path: ROUTES.ALWG_COMPARE },
//   //   { tab: 'Tech Specs', path: ROUTES.ALWG_TECH_SPECS },
//   //   { tab: 'Documentation', path: ROUTES.ALWG_DOCUMENTATION }
//   // ]

//   return (
//     <html lang="en">
//       <body
//         className={`${roboto.variable}  antialiased`}
//       >
//         {/* <Navbar allTabs={allTabs} theme='light' /> */}
//         {children}
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],

  variable: "--font-roboto",
  display: "swap",
});
export const metadata: Metadata = {
  title: {
    default: "Macnman | Industrial IoT Products Manufacturer",
    template: "%s | Macnman",
  },
  description:
    "Macnman is a leading manufacturer of Industrial IoT solutions including LoRaWAN Gateways, 4G Data Loggers, WiFi & BLE Cloud Converters. We specialize in factory automation, smart monitoring, & environmental sensing across India & globe.",
  applicationName: "Macnman IoT Devices & Cloud Solutions",
  authors: [{ name: "Macnman", url: "https://macnman.in/success-stories" }],
  keywords: [
    "LoRaWAN Gateways India",
    "4G Data Loggers",
    "Industrial IoT Sensors",
    "WiFi IoT Modules",
    "BLE to Cloud Converters",
    "RS485 to Cloud IoT",
    "IoT Products Manufacturer India",
    "Smart City IoT Devices",
    "Remote Monitoring Systems",
    "IoT Controllers for Automation",
    "Environmental Monitoring IoT",
    "LoRaWAN Sensor Modules",
    "Industrial Automation IoT",
    "Building Management IoT",
    "Asset Tracking LoRaWAN",
    "Predictive Maintenance IoT",
    "Energy Monitoring IoT",
    "Water Quality Sensors",
    "Air Quality Monitoring IoT",
    "Secure Industrial IoT Connectivity",
    "Custom IoT Product Design",
    "Factory IoT Solutions India",
  ],
  robots: "index, follow",
  openGraph: {
    type: "website",
    siteName: "Macnman",
    url: "https://macnman.in/success-stories/",
    title: "Macnman | Leading manufacturer of IoT Products",
    description:
    " Explore advanced IoT solutions: LoRaWAN, 4G, WiFi, and BLE-based smart monitoring, data logging, and cloud integrations. Visit our Pune facility or connect with our team.",
    images: [
      {
        url: "https://macnman.in/success-stories/seo_homepage.png", // After deploy URL look like this
        width: 1200,
        height: 630,
        alt: "Macnman IoT Solutions Overview",
      },
    ],
    videos: [
      {
        url: "https://macnman.in/success-stories/landing_page_1.webm",
        width: 1280,
        height: 720,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@macnman", // Our twitter handle name
    creator: "@macnman", //Creator or smae if neded
    title: "Leading manufacturer of IoT Products | Macnman",
    description:
      "Explore LoRaWAN, WiFi, and 4G IoT solutions tailored for industrial applications at Macnman.",
    images: ["https://macnman.in/success-stories/seo_homepage.png"],
  },
  alternates: { canonical: "/success-stories/" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // return (
//     <html lang="en">
//       <body
//         className={`${roboto.variable}  antialiased`}
//       >
//         {/* <Navbar allTabs={allTabs} theme='light' /> */}
//         {children}
//       </body>
//     </html>
//   );

  return (
    <html lang="en" className={`${roboto.variable}`}>
      <body className={`${roboto.variable} antialiased`}>
        
        {children}
        <div id="portal-root"></div> {/* Move portal root inside the body */}
      </body>
    </html>
  );
}